# Generated by Django 3.0.6 on 2020-05-05 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200505_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='impotant',
            new_name='important',
        ),
    ]
